# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddWindow(object):
    def setupUi(self, AddWindow):
        AddWindow.setObjectName("AddWindow")
        AddWindow.resize(462, 267)
        self.verticalLayoutWidget = QtWidgets.QWidget(AddWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 160, 361, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.AddButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.AddButton.setObjectName("AddButton")
        self.verticalLayout.addWidget(self.AddButton)
        self.CancelButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.CancelButton.setObjectName("CancelButton")
        self.verticalLayout.addWidget(self.CancelButton)
        self.HomeTeamBox = QtWidgets.QComboBox(AddWindow)
        self.HomeTeamBox.setGeometry(QtCore.QRect(120, 30, 291, 22))
        self.HomeTeamBox.setObjectName("HomeTeamBox")
        self.AwayTeamBox = QtWidgets.QComboBox(AddWindow)
        self.AwayTeamBox.setGeometry(QtCore.QRect(120, 60, 291, 22))
        self.AwayTeamBox.setObjectName("AwayTeamBox")
        self.Label = QtWidgets.QLabel(AddWindow)
        self.Label.setGeometry(QtCore.QRect(60, 60, 56, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Label.setFont(font)
        self.Label.setTextFormat(QtCore.Qt.PlainText)
        self.Label.setObjectName("Label")
        self.label = QtWidgets.QLabel(AddWindow)
        self.label.setGeometry(QtCore.QRect(20, 30, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.SeasonBox = QtWidgets.QComboBox(AddWindow)
        self.SeasonBox.setGeometry(QtCore.QRect(120, 90, 291, 22))
        self.SeasonBox.setObjectName("SeasonBox")
        self.label_2 = QtWidgets.QLabel(AddWindow)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 56, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.WinnerBox = QtWidgets.QComboBox(AddWindow)
        self.WinnerBox.setGeometry(QtCore.QRect(120, 120, 291, 22))
        self.WinnerBox.setObjectName("WinnerBox")
        self.label_3 = QtWidgets.QLabel(AddWindow)
        self.label_3.setGeometry(QtCore.QRect(30, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(AddWindow)
        QtCore.QMetaObject.connectSlotsByName(AddWindow)

    def retranslateUi(self, AddWindow):
        _translate = QtCore.QCoreApplication.translate
        AddWindow.setWindowTitle(_translate("AddWindow", "Dialog"))
        self.AddButton.setText(_translate("AddWindow", "Dodaj mecz"))
        self.CancelButton.setText(_translate("AddWindow", "Powrót"))
        self.Label.setText(_translate("AddWindow", "Gość:"))
        self.label.setText(_translate("AddWindow", "Gospodarz:"))
        self.label_2.setText(_translate("AddWindow", "Sezon:"))
        self.label_3.setText(_translate("AddWindow", "Wygrany:"))
